### ISSUE TITLE
Hide "row size" & related controls if rowSizeList is empty

### ISSUE THREAD

**Issue by kapeels** [hyojin/material-ui-datatables#22]
Allow for row size & related controls to be hidden if rowSizeList is empty.

Or, an error should be thrown because the empty dropdown looks no good. Additionally, an option to disable the controls could be added along the lines of `showHeaderToolbar`.

Let me know if you would like me to send a PR.

**Comment by hyojin** [comment]
@kapeels Sure, I would be happy if you send a PR. :) 
I think maybe we want to use just one fixed row size and show something to users in some cases. so, rather than hide all related controls, to only make dropdown hidden is better when rowSizeList is empty. And I totally agree with your idea to add an option to align with ```showHeaderToolbar``` to footer.

Thanks!
